export const LD_EventLoggerABI = [
  {
    type: 'constructor',
    inputs: [{ name: 'factoryAddress', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'logAuditorChanged',
    inputs: [
      { name: 'programId', type: 'uint256', internalType: 'uint256' },
      { name: 'missionNumber', type: 'uint256', internalType: 'uint256' },
      { name: 'oldAuditor', type: 'address', internalType: 'address' },
      { name: 'newAuditor', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'logMissionAdded',
    inputs: [
      { name: 'programId', type: 'uint256', internalType: 'uint256' },
      { name: 'newMissionNumber', type: 'uint256', internalType: 'uint256' },
      { name: 'prize', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'logPrizeAdded',
    inputs: [
      { name: 'programId', type: 'uint256', internalType: 'uint256' },
      { name: 'missionNumber', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'prize', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'logPrizeClaimed',
    inputs: [
      { name: 'programId', type: 'uint256', internalType: 'uint256' },
      { name: 'chapterIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'prize', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'logProgramCreated',
    inputs: [
      { name: 'programId', type: 'uint256', internalType: 'uint256' },
      { name: 'programAddress', type: 'address', internalType: 'address' },
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'start', type: 'uint256', internalType: 'uint256' },
      { name: 'end', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'logWithdraw',
    inputs: [
      { name: 'programId', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AuditorChanged',
    inputs: [
      { name: 'programId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'missionNumber', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'oldAuditor', type: 'address', indexed: false, internalType: 'address' },
      { name: 'newAuditor', type: 'address', indexed: false, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MissionAdded',
    inputs: [
      { name: 'programId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newMissionNumber', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'prize', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PrizeAdded',
    inputs: [
      { name: 'programId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'missionNumber', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'prize', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PrizeClaimed',
    inputs: [
      { name: 'programId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'missionNumber', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'prize', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProgramCreated',
    inputs: [
      { name: 'programId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'programAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'start', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'end', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Withdraw',
    inputs: [
      { name: 'programId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'OwnableInvalidOwner', inputs: [{ name: 'owner', type: 'address', internalType: 'address' }] },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
] as const;
