export enum ERROR_MESSAGE {
  DB_UPDATE,
  TRANSACTION_FAIL,
  TRANSACTION_REJECTED,
  UPDATE_DEPLOYED_ADDRESS,
  INVALID_VALIDATOR,
  NOT_FOUND_SIGNATURE,
  INSUFFICIENT_MISSION_RESERVE,
  FAIL_TO_FETCH_DATA_FROM_ONCHAIN,
}
